<a href="https://colab.research.google.com/github/DIVYA14797/pandas/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

consider the below code to answer further questions:  
import numpy as np  
list_=['1','2','3','4','5']      
array_list = np.array(object= list_)



1. Is there any difference in the data type of variables  list_ and array_list ? If there is  then write a code to print the data types of both the variables .


Yes, there is a difference in the data type of the variables list_ and array_list. The list_ variable contains elements of type string, while the array_list variable contains elements of type numpy.str_.

In [ ]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_ variable:", type(list_[0]))
print("Data type of array_list variable:", type(array_list[0]))

Data type of list_ variable: <class 'str'>
Data type of array_list variable: <class 'numpy.str_'>


2. Write the code to print the data type of each and every element of both the variables list_ and array_list .



In [ ]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Considering the following changes in the variable , array_list :

array_list =np.array(object=list_ , dtype =int)      .

 3. Will there be any difference in the data type of the elements present in bioth the variables , list _ and arra_list ?  If  so then print the data types of each and every element present in both the variables , list_ and arra_list .



Yes, there will be a difference in the data types of the elements present in the variables list_ and array_list. When you specify dtype=int while creating array_list, NumPy will attempt to convert the elements of list_ to integers.



In [ ]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions :    
import numpy as np   
num_list =[[1,2,3],[4,5,6,]]    
num_array = np.array(object=num_list)      

4.  Write a code to find the following characteristics of variable ,  num_array :

(i) shape     
(ii) size



In [ ]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
print("Shape of num_array:", num_array.shape)

# (ii) Size
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


5. Write a code to create numpy array of 3*3 matrix containing zeros only , using a numpy array creation function

In [ ]:
import numpy as np

# Create a 3x3 matrix of zeros
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


6. Create an identity matrix of shape(5,5) using numpy functions?

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
